### ISSUE TITLE
No issue

### ISSUE THREAD

**Issue by cgcardona** [SpendBCH/bch-stresstest#1]
Just wanted to leave you a tip w/ GitCash :)

**Comment by cgcardona** [comment]
@gitcash tip 135406 satoshis to @SpendBCH

**Comment by GitCash** [comment]
Hey **SpendBCH**, user **cgcardona** tipped you **1354 bits** in Bitcoin Cash ( ~ **$1.0142** ).

*[Click here to claim it!](https://gitcash.io/claim/SpendBCH)*

You can also add the :-1: reaction to **cgcardona**'s comment above to prevent future tips.
