### ISSUE TITLE
The mining fee for split tx calculation is off and did fail when testing 10k+ tx. Save your mnemonic to recover these funds.

### ISSUE THREAD

**Issue by SpendBCH** [SpendBCH/bch-stresstest#2]

**Comment by cgcardona** [comment]
@gitcash tip 136199 satoshis to @SpendBCH 

Thanks for the UTXO merge! 🎩

**Comment by GitCash** [comment]
Hey **SpendBCH**, user **cgcardona** tipped you **1361 bits** in Bitcoin Cash ( ~ **$0.9888** ).

*[Click here to claim it!](https://gitcash.io/claim/SpendBCH)*

You can also add the :-1: reaction to **cgcardona**'s comment above to prevent future tips.

**Comment by SpendBCH** [comment]
Current build is testing well with up to 0.013 BCH
